### ISSUE TITLE
Any way to mark a record as unread?

### ISSUE THREAD

**Issue by yesmeck** [ledermann/unread#25]
Hi, I want to mark a marked record as unread, I thinks it should be easy to add  `mark_as_unread!` method. But after dig into the code, I found that unable to mark a record as unread if I have called `SomeClass.mark_as_read! :all, for: user`. So do you have any suggestion to  implement the `mark_as_unread!` method?

**Comment by jarinudom** [comment]
Seems like the best way to go about it for items that are shared between users is to use a join table as the model for determining whether or not something is read.

For example, you might have the following (p.s. none of this is tested so it may not work):

```ruby
class User
  acts_as_reader
  has_many :participations
  has_many :conversations, through: :participations

  def unread_conversations
    Conversation.find(Participation.where(user: self).unread_by(self).pluck(:conversation_id))
  end
end

class Participation
  acts_as_readable on: :updated_at
  belongs_to :user
  belongs_to :conversation
end

class Conversation
  has_many :participations
  has_many :users, through: :participations

  def mark_unread_for(user)
    participations.where(user: user).first.touch
  end
end
```

**Comment by arusa** [comment]
For me it works this way:
`post.read_mark(current_user).destroy!`

**Comment by aried3r** [comment]
I've tried to wrap my head around this, but it feels like the solution proposed by @arusa should work, even with `.cleanup_read_marks!`, except for the fact that this method is [now private](https://github.com/ledermann/unread/commit/f51b741c39a58921c4b74a42673f93d1eae61164).

@ledermann, could you chime in on this again?

The way I see it the `read_mark(reader)` method returns the latest read mark (actually, this is not true, it doesn't use `.order` on the relation and thus no order is guaranteed in e.g. PostgreSQL:
>If sorting is not chosen, the rows will be returned in an unspecified order. 

https://www.postgresql.org/docs/9.5/static/queries-order.html)

If we delete that ReadMark, a record is unread for that user. Isn't that correct?

I might be wrong because I don't exactly know how the Garbage Collector class of this gem works completely.

**Comment by ledermann** [comment]
@aried3r, @arusa The garbage collector [`.cleanup_read_marks!`](https://github.com/ledermann/unread/blob/master/lib/unread/garbage_collector.rb) searches for the oldest unread record (if there is any). Then all read_marks before its timestamp are deleted and the global timestamp is moved. The cleanup is essential for this gem, because it keeps the number of read_marks as low as possible. I recommended to run it once a day (via a CRON job or similar).

Because old read_marks are deleted this way, we cannot mark a record as unread after a cleanup was done. Note: There are situations where it does work. Example: If you have an old unread record, the garbage collector cannot remove newer read_marks, so you can delete them manually to mark records as unread. But in a real world app, it's unlikely that a user keeps an old record unread for a long time. 

So: Without big changes in the algorithm it's not possible to mark a record as unread.
